services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build: ./forecast-frontend
    ports:
      - "8085:80"
    networks:
      - app-network
  auth-service:
    build: ./auth_service
    ports:
      - "8082:8080"
    networks:
      - app-network
  user-service:
    build: ./user_service
    ports:
      - "8083:8080"
    networks:
      - app-network

  ai-service:
    build: ./ai_service
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - app-network
    environment:                  # ← aqui sim, environment é válido
          - OPENAI_API_KEY=${OPENAI_API_KEY}
          - OPENAI_MODEL=gpt-4o-mini
          - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
    # environment:
    #   GEMINI_KEY: ${GEMINI_API_KEY}
    #   GEMINI_API_URL: ${GEMINI_API_URL}
networks:
  app-network:
    driver: bridge
# openai:
#   api:
#     key: ${OPENAI_API_KEY}


