version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8080:8080"

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8082:8080"

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: ai_service
    ports:
      - "8081:8080"
    env_file:
      - .env

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8083:8080"

  frontend:
    build:
      context: ./forecast-frontend   # pasta onde está o Angular
      dockerfile: Dockerfile
    container_name: forecast-application-frontend-1
    ports:
      - "8085:80"   # expõe o Nginx na porta 8085

