<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>

    <!-- Pai do projeto -->
    <groupId>com.forecastapp</groupId>
    <artifactId>forecast-application</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>ForecastApplication</name>
    <description>Projeto multi-módulo para microserviços</description>

    <!-- Submódulos -->
    <modules>
    	<module>ai_service</module>
    	<module>api_gateway</module>
    	<module>auth_service</module>
        <module>user_service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.5.5</spring.boot.version>
    </properties>

    <!-- Centraliza as versões -->
	 <dependencyManagement>
	    <dependencies>
	        <!-- Spring Boot BOM -->
	        <dependency>
	            <groupId>org.springframework.boot</groupId>
	            <artifactId>spring-boot-dependencies</artifactId>
	            <version>${spring.boot.version}</version>
	            <type>pom</type>
	            <scope>import</scope>
	        </dependency>
	
	        <!-- Spring Cloud BOM -->
	        <dependency>
	            <groupId>org.springframework.cloud</groupId>
	            <artifactId>spring-cloud-dependencies</artifactId>
	            <version>2023.0.3</version> <!-- versão estável compatível com Boot 3.5.x -->
	            <type>pom</type>
	            <scope>import</scope>
	        </dependency>
		 </dependencies>
	</dependencyManagement>


    <!-- Plugins comuns a todos os módulos -->
   <build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>${spring.boot.version}</version>
            <executions>
                <execution>
                    <goals>
                        <goal>repackage</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <mainClass>com.forecastapp.ForecastApplication</mainClass>
            </configuration>
        </plugin>
    </plugins>
</build>
</project>
