spring:
  datasource:
    url: jdbc:h2:mem:forecastdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente (pode trocar por validate em produção)
    show-sql: true       # exibe queries no console
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: forecast-application

server:
  port: 80

  
