spring:
  datasource:
    url: jdbc:mysql://192.168.65.2:3306/forecastdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: forecast
    password: forecast
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente (pode trocar por validate em produção)
    show-sql: true       # exibe queries no console
    properties:
      hibernate:
        format_sql: true

  application:
    name: forecast-application

server:
  port: 8080
  
