server:
  port: 8080  # O Gateway central ficará nessa porta

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: users
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: ai
          uri: http://localhost:8081
          predicates:
            - Path=/ai/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://forecast-frontend.azurewebsites.net"  # já deixa pronto p/ produção
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
