spring.application.name=ForecastApplication-ai_service
#spring.security.user.name=
#spring.security.user.password=
spring.jpa.hibernate.ddl-auto=update
eureka.instance.hostname=localhost

# Porta do serviço
server.port=8080

# Secret JWT (usar variáveis de ambiente em produção!)
jwt.secret=MeuSegredoSuperSecreto123
jwt.expiration=3600000
