server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
      path: /h2-console

# spring:
#   application:
#     name: ai-service
#   datasource:
#     url: jdbc:h2:mem:forecast_ai_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true


# usa variáveis de ambiente com valor padrão para não quebrar em dev/teste
openai:
  api:
    key: ${OPENAI_API_KEY:default-dummy-key-for-local}

# gemini:
#   api:
#     key: ${GEMINI_API_KEY:dummy-key-for-dev}
#     url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# em produção (opcional), desabilite o console H2
---
# spring:
#   config:
#     activate:
#       on-profile: prod
#   h2:
#     console:
#       enabled: false
#   security:
#     enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}


