server:
  port: 8080

spring:
  security:
    enabled: false
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth_service:8080
          predicates:
            - Path=/auth/**
        - id: users
          uri: http://user_service:8080
          predicates:
            - Path=/users/**
        - id: ai
          uri: http://ai_service:8080
          predicates:
            - Path=/chat/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8085"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
