server:
  port: ${PORT:8082}

spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
      path: /h2-console

# spring:
#   application:
#     name: auth-service
#   datasource:
#     url: jdbc:h2:mem:forecast_auth_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

# spring:
#   config:
#     activate:
#       on-profile: prod
#   h2:
#     console:
#       enabled: false


