name: CI - Build & Push Docker Images

on:
  push:
    branches: [ "forecast-application-dev" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Maven
        run: mvn -B clean package -DskipTests

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ==== API GATEWAY ====
      - name: Build & Push api_gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api_gateway
          file: ./api_gateway/Dockerfile
          push: true
          tags: |
            pedrohermes/forecast-application-api_gateway:latest

      # ==== AUTH SERVICE ====
      - name: Build & Push auth_service
        uses: docker/build-push-action@v5
        with:
          context: ./auth_service
          file: ./auth_service/Dockerfile
          push: true
          tags: |
            pedrohermes/forecast-application-auth_service:latest

      # ==== USER SERVICE ====
      - name: Build & Push user_service
        uses: docker/build-push-action@v5
        with:
          context: ./user_service
          file: ./user_service/Dockerfile
          push: true
          tags: |
            pedrohermes/forecast-application-user_service:latest

      # ==== AI SERVICE ====
      - name: Build & Push ai_service
        uses: docker/build-push-action@v5
        with:
          context: ./ai_service
          file: ./ai_service/Dockerfile
          push: true
          tags: |
            pedrohermes/forecast-application-ai_service:latest

      # ==== FRONTEND ANGULAR ====
      - name: Build & Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./forecast-frontend
          file: ./forecast-frontend/Dockerfile
          push: true
          tags: |
            pedrohermes/forecast-application-frontend:latest